spring:
  profiles.active: test
---
spring:
  profiles: test
  jackson.date-format: es.caser.archit.RFC3339DateFormat
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
  jooq.sql-dialect: POSTGRES
  cache.jcache.config: ehcache3.xml
  datasource:
     url: jdbc:postgresql://localhost:5432/pruebas
     username: postgres
     password: postgres
     driver-class-name: org.postgresql.Driver
     hikari:
        connection-timeout: 60000
        maximum-pool-size: 5       
server:
  port: 10080
  contextPath: /api

springfox.documentation.swagger.v2.path: /api-docs
spring.boot.admin.url: http://localhost:8080
spring.boot.admin.client.name: SampleApi2
liquibase:
  change-log: classpath:\liquibase\db_changelog_master.xml
endpoints:
  health:
      sensitive: false

management:
   security:
      enabled: false
   context-path: /admin

---
spring:
   profiles: pro
   jackson.date-format: es.caser.archit.RFC3339DateFormat
   jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
   jooq.sql-dialect: POSTGRES
   cache.jcache.config: ehcache3.xml
   datasource:
     url: jdbc:postgresql://localhost:5432/pruebas
     username: postgres
     password: postgres
     driver-class-name: org.postgresql.Driver
     hikari:
        connection-timeout: 60000
        maximum-pool-size: 5       
server:
  port: 8080
  contextPath: /api
    
springfox.documentation.swagger.v2.path: /api-docs  
spring.boot.admin.url: http://localhost:8080
spring.boot.admin.client.name: SampleApi2
endpoints:
  health:
      sensitive: false

management:
   security:
      enabled: false
   context-path: /admin

